#!/bin/bash
# Ghostshell PowerLevel10k Integration Script
# Automatically detects and integrates with existing PowerLevel10k, Zsh, and Fish configurations

set -e

GHOSTSHELL_CONFIG_DIR="$HOME/.config/ghostshell"
GHOSTSHELL_CONFIG="$GHOSTSHELL_CONFIG_DIR/config"
BACKUP_SUFFIX="$(date +%Y%m%d_%H%M%S)"

echo "🚀 Integrating Ghostshell with your existing shell setup..."

# Create config directory if it doesn't exist
mkdir -p "$GHOSTSHELL_CONFIG_DIR"

# Backup existing config if it exists
if [[ -f "$GHOSTSHELL_CONFIG" ]]; then
    echo "📦 Backing up existing config to $GHOSTSHELL_CONFIG.backup.$BACKUP_SUFFIX"
    cp "$GHOSTSHELL_CONFIG" "$GHOSTSHELL_CONFIG.backup.$BACKUP_SUFFIX"
fi

# Check if MesloLGS NF is installed
check_font() {
    local font_name="$1"
    if fc-list | grep -i "$font_name" > /dev/null; then
        echo "✅ Font '$font_name' is installed"
        return 0
    else
        echo "❌ Font '$font_name' is not installed"
        return 1
    fi
}

# Install MesloLGS NF if not present
install_meslo_font() {
    echo "📥 Installing MesloLGS NF font for PowerLevel10k..."
    
    local font_dir="$HOME/.local/share/fonts"
    mkdir -p "$font_dir"
    
    local fonts=(
        "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
        "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
        "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
        "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
    )
    
    for font_url in "${fonts[@]}"; do
        local font_file=$(basename "$font_url" | sed 's/%20/ /g')
        if [[ ! -f "$font_dir/$font_file" ]]; then
            echo "  Downloading $font_file..."
            curl -L -o "$font_dir/$font_file" "$font_url"
        fi
    done
    
    # Refresh font cache
    fc-cache -f "$font_dir"
    echo "✅ MesloLGS NF font installed successfully"
}

# Check and install font
if ! check_font "MesloLGS NF"; then
    if command -v curl >/dev/null 2>&1; then
        install_meslo_font
    else
        echo "❌ curl is required to install fonts automatically"
        echo "   Please install MesloLGS NF manually from:"
        echo "   https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k"
    fi
fi

# Create optimized Ghostshell config for PowerLevel10k
echo "⚙️  Creating optimized Ghostshell configuration..."

cat > "$GHOSTSHELL_CONFIG" << 'EOF'
# Ghostshell PowerLevel10k Optimized Configuration
# Generated by setup-powerlevel10k.sh

# PowerLevel10k Font Configuration
font-family = "MesloLGS NF"
font-size = 12
font-feature = +liga
font-feature = +calt
font-feature = +kern

# Performance optimizations for PowerLevel10k
fps-cap = 120
vsync = true
scrollback-limit = 100000

# Shell integration for PowerLevel10k
shell-integration = zsh
shell-integration-features = cursor,sudo,title

# Cursor optimizations
cursor-style = beam
cursor-style-blink = false

# Theme (Dracula-inspired for PowerLevel10k)
foreground = #f8f8f2
background = #282a36

# Color palette optimized for PowerLevel10k segments
palette = 0=#44475a  # Black
palette = 1=#ff5555  # Red
palette = 2=#50fa7b  # Green
palette = 3=#f1fa8c  # Yellow
palette = 4=#6272a4  # Blue
palette = 5=#ff79c6  # Magenta
palette = 6=#8be9fd  # Cyan
palette = 7=#f8f8f2  # White
palette = 8=#44475a  # Bright Black
palette = 9=#ff5555  # Bright Red
palette = 10=#50fa7b # Bright Green
palette = 11=#f1fa8c # Bright Yellow
palette = 12=#6272a4 # Bright Blue
palette = 13=#ff79c6 # Bright Magenta
palette = 14=#8be9fd # Bright Cyan
palette = 15=#ffffff # Bright White

# Wayland optimizations
wayland-app-id = com.ghostkellz.ghostshell
window-decoration = true
gtk-titlebar = false

# NVIDIA optimizations
window-vsync = true
window-inherit-working-directory = true
EOF

echo "✅ Ghostshell configuration created at $GHOSTSHELL_CONFIG"

# Check if PowerLevel10k is installed
check_powerlevel10k() {
    if [[ -f "$HOME/.p10k.zsh" ]] || [[ -n "$POWERLEVEL9K_CONFIG_FILE" ]]; then
        echo "✅ PowerLevel10k appears to be installed"
        return 0
    fi
    
    if [[ -f "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]] || \
       [[ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]]; then
        echo "✅ PowerLevel10k appears to be installed (Oh My Zsh)"
        return 0
    fi
    
    echo "⚠️  PowerLevel10k not detected"
    return 1
}

# Provide PowerLevel10k installation instructions if not found
if ! check_powerlevel10k; then
    echo ""
    echo "🔧 To complete the setup, install PowerLevel10k:"
    echo ""
    echo "   For Oh My Zsh:"
    echo "   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git \${ZSH_CUSTOM:-\$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
    echo "   # Then set ZSH_THEME=\"powerlevel10k/powerlevel10k\" in ~/.zshrc"
    echo ""
    echo "   For manual installation:"
    echo "   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k"
    echo "   echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc"
    echo ""
fi

echo ""
echo "🎉 Ghostshell PowerLevel10k setup complete!"
echo ""
echo "Next steps:"
echo "1. Restart your terminal or run: ghostshell"
echo "2. If PowerLevel10k configuration wizard appears, choose options that match your preference"
echo "3. Enjoy the optimized PowerLevel10k experience in Ghostshell!"
echo ""
echo "💡 Pro tip: The MesloLGS NF font provides the best icon and symbol rendering for PowerLevel10k"